"""Generate the worker Squid policy, including exact local endpoint destinations."""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import time
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from crucible.domain.endpoints import validate_endpoint


def enabled_local_endpoints(routing_policies: Sequence[Mapping[str, Any]]) -> list[str]:
    """Return the distinct URLs authorized by enabled local routing entries."""
    endpoints: list[str] = []
    for policy in routing_policies:
        for model in policy.get("models", []):
            if not isinstance(model, Mapping):
                continue
            endpoint = model.get("endpoint_url")
            if model.get("enabled") is True and model.get("endpoint") == "local":
                if not isinstance(endpoint, str):
                    raise ValueError("an enabled local routing entry requires endpoint_url")
                validate_endpoint("local", endpoint)
                if endpoint not in endpoints:
                    endpoints.append(endpoint)
    return endpoints


def worker_proxy_config(
    subnet: str, hosts: list[str], routing_policies: Sequence[Mapping[str, Any]]
) -> str:
    lines = [
        "# Generated by 'make proxy-config'.",
        f"acl workers src {subnet}",
        "acl SSL_ports port 443",
        "acl Safe_ports port 443",
    ]
    local_rules: list[tuple[str, int, str]] = []
    for index, endpoint in enumerate(enabled_local_endpoints(routing_policies)):
        parsed = urlsplit(endpoint)
        if parsed.scheme not in ("http", "https"):
            raise ValueError("local model proxy destinations must use HTTP or HTTPS")
        assert parsed.hostname is not None
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        try:
            address = ipaddress.ip_address(parsed.hostname)
            destination = f"{address}/{32 if address.version == 4 else 128}"
            acl_kind = "dst"
        except ValueError:
            destination = parsed.hostname
            acl_kind = "dstdomain"
        lines.extend(
            [
                f"acl local_destination_{index} {acl_kind} {destination}",
                f"acl local_port_{index} port {port}",
                f"acl Safe_ports port {port}",
            ]
        )
        if parsed.scheme == "https" and port != 443:
            lines.append(f"acl SSL_ports port {port}")
        local_rules.append((f"local_destination_{index}", port, f"local_port_{index}"))
    lines.append("acl CONNECT method CONNECT")
    lines.extend(f"acl allowed dstdomain {host}" for host in hosts)
    lines.extend(["http_access deny !Safe_ports", "http_access deny CONNECT !SSL_ports"])
    for destination, _port, port_acl in local_rules:
        lines.append(f"http_access allow workers {destination} {port_acl}")
    lines.extend(
        [
            "http_access allow workers CONNECT allowed",
            "http_access deny all",
            "http_port 3128",
            "cache deny all",
            "access_log /var/log/squid/access.log",
            "pid_filename /run/squid.pid",
            "shutdown_lifetime 1 second",
        ]
    )
    return "\n".join(lines) + "\n"


def install_worker_proxy_config(
    path: Path, rendered: str, *, reload_timeout_seconds: float = 0
) -> None:
    """Atomically replace worker proxy rules, then request a live reload."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.incoming")
    descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(rendered)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)
    marker = path.parent / "reload"
    marker_temporary = marker.with_name(".reload.incoming")
    token = f"{time.time_ns()}-{os.getpid()}"
    marker_temporary.write_text(f"{token}\n", encoding="ascii")
    os.replace(marker_temporary, marker)
    if reload_timeout_seconds <= 0:
        return
    deadline = time.monotonic() + reload_timeout_seconds
    acknowledged = path.parent / "reloaded"
    while time.monotonic() < deadline:
        try:
            if acknowledged.read_text(encoding="ascii").strip() == token:
                return
        except OSError:
            pass
        time.sleep(0.05)
    raise TimeoutError("the egress proxy did not acknowledge the new configuration")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--subnet", required=True)
    parser.add_argument("--host", action="append", default=[])
    parser.add_argument("--routing-policy", action="append", type=Path, default=[])
    args = parser.parse_args()
    routing_policies: list[Mapping[str, Any]] = []
    for path in args.routing_policy:
        loaded = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(loaded, dict):
            raise ValueError(f"routing policy {path} must contain a JSON object")
        document = loaded.get("document", loaded)
        if not isinstance(document, dict):
            raise ValueError(f"routing policy {path} has no object document")
        routing_policies.append(document)
    install_worker_proxy_config(
        args.output, worker_proxy_config(args.subnet, args.host, routing_policies)
    )


if __name__ == "__main__":
    main()
