# Same targets locally and in CI (18). One definition, two callers.
#
# Crucible runs on the dedicated rootless daemon of the `crucible` service user
# (13, ADR 0004, S9). Point DOCKER at that daemon before running anything that
# creates containers. On the reference workstation the service user has no login
# shell, so the operator's wrapper is:
#
#   make e2e DOCKER='sudo -u crucible -H env HOME=/var/lib/crucible-docker \
#     XDG_RUNTIME_DIR=/run/user/999 DOCKER_HOST=unix:///run/user/999/docker.sock docker'
#
# CI has an ordinary rootful daemon and needs none of that: DOCKER stays `docker`.
DOCKER ?= docker
COMPOSE ?= $(DOCKER) compose
UV ?= uv

# The rootless daemon's socket, derived, never hardcoded: the uid differs per host (S9).
CRUCIBLE_UID := $(shell id -u crucible 2>/dev/null)
CRUCIBLE_DOCKER_SOCKET ?= $(if $(CRUCIBLE_UID),/run/user/$(CRUCIBLE_UID)/docker.sock,/var/run/docker.sock)
export CRUCIBLE_DOCKER_SOCKET

# The hostnames the egress proxy permits: the union of the policy's egress_allowlist
# and the adapters' declared model endpoints (13, S6). `proxy-config` writes the squid
# configuration from this list and Crucible refuses to launch an attempt that needs a
# host the running proxy does not permit.
EGRESS_ALLOWLIST ?= github.com objects.githubusercontent.com pypi.org files.pythonhosted.org registry.npmjs.org api.anthropic.com api.openai.com auth.openai.com daily-cloudcode-pa.googleapis.com oauth2.googleapis.com
WORKERS_SUBNET ?= 10.88.0.0/24

.PHONY: up dev down reset lint scan scan-tree scan-history smoke test test-unit \
	test-integration e2e e2e-image build proxy-config proxies preflight

up: preflight proxy-config ## normal mode: postgres, proxies, migrate, crucible
	@test -f .env || cp .env.example .env
	$(COMPOSE) up -d --build --wait

dev: preflight proxy-config ## developer mode: postgres and the two proxies; run `uv run crucible serve --all` on the host
	@test -f .env || cp .env.example .env
	$(COMPOSE) -f compose.yaml -f compose.dev.yaml --profile dev up -d --wait

preflight: ## S9 follow-up 1: say what is wrong rather than letting compose be cryptic
	@test -n "$(CRUCIBLE_UID)" \
	  || echo "preflight: no 'crucible' service user, so this is ADR 0004's fallback: the host daemon behind the proxy. A compromise of Crucible is then a compromise of the host (13)."
	@test -S "$(CRUCIBLE_DOCKER_SOCKET)" || { echo "preflight: no docker socket at $(CRUCIBLE_DOCKER_SOCKET)"; exit 2; }
	@test -f /etc/apparmor.d/rootlesskit || echo "preflight: warning, /etc/apparmor.d/rootlesskit is missing; the rootless daemon will not start after a reboot on Ubuntu 24.04 (S9)"
	@$(DOCKER) info --format '{{range .SecurityOptions}}{{.}} {{end}}' 2>/dev/null | grep -q rootless \
	  || echo "preflight: warning, DOCKER is not pointed at a rootless daemon"
	@$(DOCKER) info --format '{{.CgroupVersion}}' 2>/dev/null | grep -q '^2$$' \
	  || echo "preflight: warning, cgroup v2 is what the memory and pids limits need (05b, S9)"

proxy-config: ## write the egress proxy's allowlist from EGRESS_ALLOWLIST (13, S6)
	@mkdir -p var/egress
	@{ \
	  echo "# Generated by 'make proxy-config'. The allowlist is the union of the policy's"; \
	  echo "# egress_allowlist and the adapters' declared model endpoints (13, S6)."; \
	  echo "acl workers src $(WORKERS_SUBNET)"; \
	  echo "acl SSL_ports port 443"; \
	  echo "acl Safe_ports port 443"; \
	  echo "acl CONNECT method CONNECT"; \
	  for host in $(EGRESS_ALLOWLIST); do echo "acl allowed dstdomain $$host"; done; \
	  echo "http_access deny !Safe_ports"; \
	  echo "http_access deny CONNECT !SSL_ports"; \
	  echo "http_access allow workers CONNECT allowed"; \
	  echo "http_access deny all"; \
	  echo "http_port 3128"; \
	  echo "cache deny all"; \
	  echo "# squid drops to the unprivileged 'proxy' user before it opens its logs, so"; \
	  echo "# /dev/stdout fails (S9). The image's entrypoint tails this file into the"; \
	  echo "# container log, which is where every CONNECT decision is read."; \
	  echo "access_log /var/log/squid/access.log"; \
	  echo "pid_filename none"; \
	  echo "shutdown_lifetime 1 second"; \
	} > var/egress/squid.conf
	@echo "wrote var/egress/squid.conf with $(words $(EGRESS_ALLOWLIST)) allowed hostname(s)"

proxies: preflight proxy-config ## bring up only the socket proxy and the egress proxy
	@test -f .env || cp .env.example .env
	$(COMPOSE) up -d docker-socket-proxy egress-proxy

down:
	$(COMPOSE) --profile "*" down

reset: ## DESTRUCTIVE: down plus the postgres and artifact volumes; the only cure for schema drift
	$(COMPOSE) --profile "*" down --volumes

lint:
	$(UV) sync --frozen --quiet
	$(UV) run ruff format --check crucible tests tools/smoke
	$(UV) run ruff check crucible tests tools/smoke
	$(UV) run mypy crucible tests tools/smoke
	$(UV) run lint-imports

scan: scan-tree scan-history ## secret scan; needs gitleaks on PATH

scan-tree: ## every tracked file as it is in the working tree (caches and .venv excluded)
	@T=$$(mktemp -d) && git ls-files -z | tar --null -T - -cf - | tar -xf - -C "$$T" \
	  && gitleaks detect --no-git --redact --no-banner --source "$$T"; S=$$?; rm -rf "$$T"; exit $$S

scan-history: ## commits in SCAN_RANGE (default origin/main..HEAD)
	gitleaks detect --redact --no-banner --source . --log-opts="$${SCAN_RANGE:-origin/main..HEAD}"

smoke: ## drive one task end to end through a running stack; `make up` first
	@test -f .env || cp .env.example .env
	COMPOSE="$(COMPOSE)" $(if $(CRUCIBLE_IMAGE),CRUCIBLE_IMAGE="$(CRUCIBLE_IMAGE)") \
	  python3 tools/smoke/compose_smoke.py

test: test-unit test-integration

test-unit:
	$(UV) sync --frozen --quiet
	$(UV) run pytest tests/unit -q

test-integration: ## needs Docker for postgres:16 (testcontainers) or CRUCIBLE_TEST_DATABASE_URL
	$(UV) sync --frozen --quiet
	$(UV) run pytest tests/integration -q -m integration

e2e-image: ## build the e2e worker image (18) on whichever daemon DOCKER names
	DOCKER_HOST=$${DOCKER_HOST:-} images/build.sh script-harness

e2e: ## the Docker-provider end-to-end tier (18): real containers, no model
	$(UV) sync --frozen --quiet
	CRUCIBLE_E2E_DOCKER="$(DOCKER)" \
	CRUCIBLE_E2E_DOCKER_SOCKET="$(CRUCIBLE_DOCKER_SOCKET)" \
	$(UV) run pytest tests/e2e -q -m e2e

build:
	docker build -t crucible:dev .
