apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - github-app-rbac.yaml
  - configmap.yaml
  - artifacts-pvc.yaml
  - postgres.yaml
  - migrate-job.yaml
  - api.yaml
  - supervisor.yaml
