"""Capture the command trees of the two clients `crucible` replaced, for the parity test.

Run once, by hand, against the sources named on the command line; the output is
committed next to this file and never regenerated by the test itself, so the test holds
the new command to the old trees even after the old code is gone:

    uv run python tests/fixtures_data/legacy_cli/capture.py \\
        --admin-source <crucible-admin's admin.py at the base commit> \\
        --foundry-source <foundry-crucible's foundry_crucible/cli.py> \\
        --admin-ref 6198913 --foundry-ref <foundry commit> > trees.json
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any


def walk(parser: argparse.ArgumentParser, path: tuple[str, ...] = ()) -> dict[str, Any]:
    """Every leaf command: its path, positionals, and options with their shape."""
    tree: dict[str, Any] = {}
    positionals: list[str] = []
    options: dict[str, dict[str, Any]] = {}
    children: dict[str, argparse.ArgumentParser] = {}
    for act in parser._actions:
        if isinstance(act, argparse._HelpAction):
            continue
        if isinstance(act, argparse._SubParsersAction):
            children.update(act.choices)
            continue
        if not act.option_strings:
            positionals.append(act.dest)
            continue
        options[max(act.option_strings, key=len)] = {
            "dest": act.dest,
            "required": bool(act.required),
            "flag": isinstance(act, argparse._StoreTrueAction),
            "choices": sorted(act.choices) if act.choices else None,
            "type": getattr(act.type, "__name__", None),
            "default": act.default if isinstance(act.default, (str, int, bool)) else None,
        }
    tree[" ".join(path)] = {"positionals": positionals, "options": options}
    for name, child in children.items():
        tree.update(walk(child, (*path, name)))
    return tree


def load(source: Path, name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, source)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--admin-source", type=Path, required=True)
    parser.add_argument("--foundry-source", type=Path, required=True)
    parser.add_argument("--admin-ref", required=True)
    parser.add_argument("--foundry-ref", required=True)
    args = parser.parse_args()
    admin = load(args.admin_source, "legacy_crucible_admin")
    foundry = load(args.foundry_source, "legacy_foundry_crucible")
    document = {
        "crucible-admin": {"ref": args.admin_ref, "tree": walk(admin.build_parser())},
        "foundry-crucible": {"ref": args.foundry_ref, "tree": walk(foundry.build_parser())},
    }
    json.dump(document, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
